services:
  mysql:
    image: mysql:8.4
    container_name: mysql-nlw_connect
    environment:
      - MYSQL_ROOT_PASSWORD=mysql
    ports: 
      - '3306:3306'
    networks: 
      - nlw-network
networks:
  nlw-network:
    driver: bridge